name: Update Badges
on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: harish-kumar-johnson
